### ISSUE TITLE
Stop submit new task when closing libp2p

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/libp2p#64]
#### System information

Libp2p version: v2.0.0\
OS & Version: Linux & macOS

#### Expected Behavior

When libp2p is closing, stop submitting any new task to `ScheduledExecutorService`. such as `ConnPoolService` should not trigger a new TCP connection.

#### Actual Behavior

When libp2p is closing, `ConnPoolService` will execute `close` to eliminate all active channels in turn. At this time the close event is caught, a task of initiating TCP connection is triggered and will be added to `ScheduledExecutorService` `poolLoopExecutor` of `ConnPoolService` by the method `triggerConnect` of `ChannelManager` subsequently, exception of java.util.concurrent.RejectedExecutionException will be caught.

![image](https://github.com/tronprotocol/libp2p/assets/23312631/07fa34d0-fce7-4d94-ad64-defa5bb6578f)

This is not excepted. Once closing libp2p, any new TCP connection should not be triggered. Another example is that NodeDetectService tries to submit a new detect task when libp2p is closing.

#### Steps to Reproduce the Behavior

When java-tron fullnode with libp2p is running, use the command kill -15 \<pid> to shut down the node.

#### Backtrace

Exception log 1:

    13:08:45.935 ERROR [pool-64-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
    java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:987)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:491)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:333)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
        at org.tron.p2p.connection.socket.PeerClient.connectAsync(PeerClient.java:92)
        at org.tron.p2p.connection.socket.PeerClient.connectAsync(PeerClient.java:62)
        at org.tron.p2p.connection.business.pool.ConnPoolService.lambda$connect$4(ConnPoolService.java:189)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.tron.p2p.connection.business.pool.ConnPoolService.connect(ConnPoolService.java:187)
        at org.tron.p2p.connection.business.pool.ConnPoolService.lambda$triggerConnect$9(ConnPoolService.java:267)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Exception log 2:

    11:35:22.699 ERROR [pool-65-thread-1] [i.n.u.c.D.rejectedExecution](Slf4JLogger.java:181) Failed to submit a listener notification task. Event loop shut down?
    java.util.concurrent.RejectedExecutionException: event executor terminated
            at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842)
            at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328)
            at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321)
            at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
            at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768)
            at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
            at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
            at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
            at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
            at org.tron.p2p.connection.socket.PeerClient.connectAsync(PeerClient.java:66)
            at org.tron.p2p.connection.business.detect.NodeDetectService.detect(NodeDetectService.java:131)
            at org.tron.p2p.connection.business.detect.NodeDetectService.work(NodeDetectService.java:93)
            at org.tron.p2p.connection.business.detect.NodeDetectService.lambda$init$0(NodeDetectService.java:58)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

Exception log 3:
```
18:38:30.815 WARN  [pool-63-thread-1] [i.n.c.AbstractChannel](AbstractChannel.java:490) Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x7b14b9c9]
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351)
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:483)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
        at org.tron.p2p.connection.socket.PeerClient.connectAsync(PeerClient.java:97)
        at org.tron.p2p.connection.socket.PeerClient.connectAsync(PeerClient.java:64)
        at org.tron.p2p.connection.business.pool.ConnPoolService.lambda$connect$4(ConnPoolService.java:190)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.tron.p2p.connection.business.pool.ConnPoolService.connect(ConnPoolService.java:188)
        at org.tron.p2p.connection.business.pool.ConnPoolService.lambda$triggerConnect$9(ConnPoolService.java:269)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wubin01** [comment]
@317787106 This should be a concurrency issue, is there any good way to control this concurrency?

**Comment by chengtx01** [comment]
@317787106 Is this issue only caused by triggering connect when libp2p is closed? Will the scheduled task of poolLoopExecutor also trigger this issue?

**Comment by lurais** [comment]
@317787106 Actually, should you just catch this Exception for we can not know the status of the executor without some locks ?

**Comment by 317787106** [comment]
> @317787106 Is this issue only caused by triggering connect when libp2p is closed? Will the scheduled task of poolLoopExecutor also trigger this issue?

@chengtx01 No, any task that submited when libp2p is closing will cause this problem. Triggering connect is one example scene.

**Comment by 317787106** [comment]
> @317787106 Actually, should you just catch this Exception for we can not know the status of the executor without some locks ?

This exception couldn't be catched. It is thrown by the third party.

**Comment by 317787106** [comment]
> @317787106 This should be a concurrency issue, is there any good way to control this concurrency?

@wubin01 Add a shutdown hook and set a tag. Query the tag before submiting new task.

**Comment by lurais** [comment]
> > @317787106 Actually, should you just catch this Exception for we can not know the status of the executor without some locks ?
> 
> This exception couldn't be catched. It is thrown by the third party.

But you can try to catch the certain RejectedExecutionException when use it for that not often happen ,such as poolLoopExecutor.submit.

**Comment by 317787106** [comment]
> > > @317787106 Actually, should you just catch this Exception for we can not know the status of the executor without some locks ?
> > 
> > 
> > This exception couldn't be catched. It is thrown by the third party.
> 
> But you can try to catch the certain RejectedExecutionException when use it for that not often happen ,such as poolLoopExecutor.submit.

Good iead, I will try it.

**Comment by lurais** [comment]
> > > > @317787106 Actually, should you just catch this Exception for we can not know the status of the executor without some locks ?
> > > 
> > > 
> > > This exception couldn't be catched. It is thrown by the third party.
> > 
> > 
> > But you can try to catch the certain RejectedExecutionException when use it for that not often happen ,such as poolLoopExecutor.submit.
> 
> I have tried it, RejectedExecutionException cannot be catched really.

That's confused, as I wrote a demo and caught this kind of exception finally.

**Comment by 317787106** [comment]
> 

The RejectedExecutionException of invoking sumit method explicitly can be caught. But the RejectedExecutionException of PeerClient.connectAsync cannot be catched.
